<?php
/**
 * Script and style helpers.
 *
 * @package Sobolewski\ImageIcons
 */

declare( strict_types=1 );

namespace Sobolewski\ImageIcons\Core;

defined( 'ABSPATH' ) || exit;

/**
 * Reads the *.asset.php metadata generated by @wordpress/scripts, so dependencies and
 * cache busting always match the actual build.
 */
final class Assets {

	/**
	 * Build metadata for an asset: its dependencies and version.
	 *
	 * @param string $handle_file File name without extension, for example "admin".
	 *
	 * @return array{dependencies: string[], version: string}
	 */
	public function meta( string $handle_file ): array {
		$path = IMAGE_ICONS_DIR . 'build/' . $handle_file . '.asset.php';

		if ( is_readable( $path ) ) {
			$meta = require $path;

			if ( is_array( $meta ) ) {
				return array(
					'dependencies' => isset( $meta['dependencies'] ) ? (array) $meta['dependencies'] : array(),
					'version'      => isset( $meta['version'] ) ? (string) $meta['version'] : IMAGE_ICONS_VERSION,
				);
			}
		}

		return array(
			'dependencies' => array(),
			'version'      => IMAGE_ICONS_VERSION,
		);
	}

	/**
	 * Whether a build file exists.
	 *
	 * @param string $relative Path relative to the plugin directory.
	 */
	public function exists( string $relative ): bool {
		return is_readable( IMAGE_ICONS_DIR . ltrim( $relative, '/' ) );
	}

	/**
	 * URL of a plugin file.
	 *
	 * @param string $relative Path relative to the plugin directory.
	 */
	public function url( string $relative ): string {
		return IMAGE_ICONS_URL . ltrim( $relative, '/' );
	}
}
